repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v3.4.0"
    hooks:
      - id: check-merge-conflict
        stages: [commit, push]
      - id: check-ast
        stages: [commit]

  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black
        language: system
        types: [python]
        stages: [commit]

      - id: isort
        name: isort
        entry: poetry run isort --filter-files
        language: system
        types: [python]
        stages: [commit]
