[tool.poetry]
name = "vkwave-api"
version = "0.1.0"
description = ""
authors = ["prostomarkeloff"]
include = ["vkwave_api/py.typed"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
